name: 'globamart'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]

models:
  globalmart:
    example:
       +materialized: table

    reporting:
       +materialized: table 

clean-targets:
       - "target"
       - "dbt_packages"

      
       

