version: 2

sources:
  - name: siera
    database: RAW
    schema: GLOBALMART
    tables:
      - name: customer
      - name: lineitem
      - name: orders
        freshness:
          error_after:
            count: 1
            period: day
          #filter: <boolean_sql_expression>
        loaded_at_field: O_ORDERDATE
      


  